GL_INCLUDE = /usr/X11R6/include
GL_LIB = /usr/X11R6/lib

main: main.o
	g++ -o main $^ -L$(GL_LIB) -lm -lGL -lglfw -lGLEW

.cpp.o:
	g++ -std=gnu++0x -c -o $@ $< -I$(GL_INCLUDE) -Iinclude

clean:
	rm -f main *.o
